[WIP]チャプター８途中です。
annatakatsuka/training.frontend pull request #8
Opened 2017-04-19 10:01 UTC by annatakatsuka

フォームの仕組みに学んでいます。
フォームの種類、CSSの適用など
テキストエリアラジオボタンとチェックボックスについて学んだので、次はプルダウンメニューからです。

2017-04-21 07:31 UTC, gkoyama requested changes
Chapter8-1jがないですがコミットしてますか？

2017-04-21 07:36 UTC, annatakatsuka commented
すみません、していません。
ファイルがないので誤って消してしまったようでです。
前回と同じミスをしてしまいすみません、コミットし直します。
次回からきをつけます。

2017-04-21 10:07 UTC, annatakatsuka commented
不足ファイル追加しました。
すみません、よろしくお願いします。

2017-04-21 10:16 UTC, gkoyama approved these changes
OKです！
修正確認しました！

2017-04-21 10:16 UTC, gkoyama commented on HTML.CSS/01.Basic/Chapter8/Chapter8-1j.html
> +        .input-group{
半角スペースがない。
焦らず確認して進めましょうね！
これは修正したらそのままマージしてOKです！

2017-04-24 08:20 UTC, gkoyama approved these changes
OKです！

2017-04-25 07:15 UTC, merged